### PR TITLE
BZ-1275620: AssetMgmt: Names of files to be promoted not visible

### PR DESCRIPTION
**Pull request by pefernan**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
It's a change to a View, so no need to provide tests.

**Comment by pefernan** [comment]
@manstis right! BTW I moved the component to MVP + tests on https://github.com/droolsjbpm/guvnor/pull/181

**Comment by csadilek** [comment]
Thanks! I resolved the conflicts myself to save another round trip. I was easy enough but please double-check.

master: 83b52d4df0b2d8efdb268e016b633d0b1dabe269

**Pull request closed without merging**
