### PR TITLE
Remove unused guvnor-webapp

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by mrietveld** [comment]
+10!

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
not merging, waiting for @manstis and @Rikkola to see if there are any objections ;).

**Comment by manstis** [comment]
@csadilek @psiroky No objections here.. but IIRC I saw @mrietveld talking to someone (in QE?) about moving some REST based tests here (from ```kie-wb-distributions``` or one of the ```-integration``` repos).. Marco?

**Comment by mrietveld** [comment]
@manstis Good ear? eye? ;) We already talked about the guvnor-webapp going away. The integration tests will be using the kie-{drools,}-wb wars. 

@livthomas @jhrcek ^^

**Pull request merged**
