### PR TITLE
GUVNOR-2259 - Correctly limiting parameters to the Guvnor REST operations

### PR DESCRIPTION
**Pull request by mrietveld**
Please let me know if you think this is a good idea? 

@Rikkola, @manstis, let me know..

### CODE REVIEW

**Comment by mrietveld** [comment]
Will add unicode tests..

**Comment by manstis** [comment]
@mrietveld Please ping me when you've added the i18n tests.

**Comment by porcelli** [comment]
@mrietveld is this still relevant?

**Comment by mrietveld** [comment]
I give up: I haven't been able to find a valid way to test i18n.

**Pull request closed without merging**
