### PR TITLE
DROOLS-1374: Rename property version.wildfly.swarm to version.org.wil…

### PR DESCRIPTION
**Pull request by mbiarnes**
…dfly.swarm
needs to be merged with: droolsjbpm/droolsjbpm-build-bootstrap#339

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
will only run properly if droolsjbpm/droolsjbpm-build-bootstrap#339 was merged before

**Comment by psiroky** [comment]
We can't really merge just one of the PRs. The build would get immediately broken.

**Comment by csadilek** [comment]
@mbiarnes the branch names still don't line up. The other branch is called wildflySwarm and this one rename_org.wildfly.swarm ;).

**Pull request closed without merging**
