### PR TITLE
Guvnor2279 squashed

### PR DESCRIPTION
**Pull request by afcollins**
@manstis Rebasing GUVNOR-2279 topic branch on master after all formatting and changes are sorted out.

### CODE REVIEW

**Comment by manstis** [comment]
@afcollins Looks fine - but can you please squash the 8 commits into a single?

**Comment by manstis** [comment]
ok to test

**Comment by afcollins** [comment]
I can do this, but your contributions will be lost, and it will appear as all my changes.  This is OK?

**Comment by manstis** [comment]
Yes, sure. No problem. I have enough commit "blames" not to worry about a
couple extra ;-) I was only trying to help you mock Aether :-)

**Comment by manstis** [comment]
By the way, in case you didnt know, you can push to your fork with -f after
squashing locally to update the PR..

**Comment by afcollins** [comment]
Okay. Submitted new PR. Should I do so to push in this PR?

**Comment by manstis** [comment]
No thanks - I'll get one of our admits to close it tomorrow when I'm at my
laptop.

**Pull request closed without merging**
