### PR TITLE
GUVNOR-2329: Added missing title

### PR DESCRIPTION
**Pull request by jomarko**
Please do not merge yet

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko Sorry, there are compilation errors relating directly to the changes made in your PR.

**Comment by jomarko** [comment]
@manstis Should be compiled without errors now.

**Comment by manstis** [comment]
jenkins retest this

**Comment by jomarko** [comment]
@manstis any problem with this PR?

**Comment by manstis** [comment]
@jomarko No problem :)

+1 to merge.

**Comment by csadilek** [comment]
master: b678c8f9abfbb809014c34857f7f1b25e8681060

**Pull request closed without merging**
