### PR TITLE
GUVNOR-2522 : NPE after entering authoring perspective / creating new project

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/GUVNOR-2522

Related:
https://github.com/droolsjbpm/kie-wb-common/pull/369

While fixing the actual bug. I had doubts about RepositoryStructureServices.load(Repository,Branch) and branch not always being set up. I tried to change the code so that all the possible scenarios where load is used are safe.

While there RepositoryConfigurationPresenter had quite a lot in it. So moved few parts to new classes.

### CODE REVIEW

**Comment by Rikkola** [comment]
Guvnor changes could be have a different ticket if that is preferred?

**Comment by manstis** [comment]
@Rikkola If it relates to the same issue; then the same JIRA number is fine.

**Comment by Rikkola** [comment]
Ok, I made a new Jira ticket just in case. Linking it to the related tickets
https://issues.jboss.org/browse/GUVNOR-2531

**Comment by Rikkola** [comment]
Need to check how tests go. I skipped kie-wb-distribution build locally. That might fail.

Other than that the PRs are ready for review.

**Comment by manstis** [comment]
+1 to merge. @Rikkola ```kie-wb-distributions``` appears unaffected! :+1:

**Pull request merged**
