### PR TITLE
Move injection to constructor for Bob Brodt

### PR DESCRIPTION
**Pull request by manstis**
@bbrodt would like this change to make his life easier.

### CODE REVIEW

**Comment by manstis** [comment]
Hi @bbrodt if you can confirm this change fits your needs I'll merge it into master.

**Comment by bbrodt** [comment]
Hi @manstis I see SessionInfo is no longer @Injected - is that a problem for existing code?

**Comment by manstis** [comment]
@bbrodt Hi.. the constructor is marked with ```@Inject``` so CDI will inject all parameters; but now you can also re-use and pass explicit constructor parameters. I also tested the change.. and everything still works :-)

**Comment by bbrodt** [comment]
Ah right, I didn't catch that. Awesome, ship it!

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
