### PR TITLE
[6.3.x] Bug 1316566 - User can not create projects in any other repository than master

### PR DESCRIPTION
**Pull request by Rikkola**
Ticket for this branch is here: https://bugzilla.redhat.com/show_bug.cgi?id=1316566

Same as in master. Had to do some small adjustments to make it fit into 6.3.x.

(cherry picked from commit 21536e2b85d46a938f842d27f70164cedcb5dfd7)

https://github.com/droolsjbpm/guvnor/pull/286
https://github.com/droolsjbpm/kie-wb-common/pull/310
https://github.com/droolsjbpm/drools-wb/pull/144
https://github.com/droolsjbpm/jbpm-console-ng/pull/365
https://github.com/droolsjbpm/kie-wb-distributions/pull/229

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by Rikkola** [comment]
So, this and the previous branch work is for the next patch not the current one. I was too eager to push the changes in thinking the previous one was already done.
The branches are already corrupted, but to help keep the changes in minimum and to help keep the cherry-picking to the current patch tag. Best to hold these 6.3.x PRs for now.

**Comment by Rikkola** [comment]
These commits can go in now. I'll rebase the branches and change the titles.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
+1 to merge.. @csadilek all yours!

**Pull request merged**
