### PR TITLE
BZ-1275620: AssetMgmt: Names of files to be promoted not visible

### PR DESCRIPTION
**Pull request by pefernan**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
It's a change to a View, so no need to provide tests.

**Comment by pefernan** [comment]
@manstis right! BTW I moved the component to MVP + tests on https://github.com/droolsjbpm/guvnor/pull/180

**Comment by csadilek** [comment]
Thanks!

6.3.x: 8d473c68f8ce6919000bd1ea5f777f94608ff2e3

**Pull request closed without merging**
