### PR TITLE
[6.4.x] BPMSPL-252: [GSS-RFE] Ability to check duplicate of ReleaseId (GroupId, ArtifactId and Version) with existing projects

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/BPMSPL-252

This is the PR for 6.4.x.

### CODE REVIEW

**Comment by manstis** [comment]
Part of the following ensemble:

https://github.com/droolsjbpm/drools/pull/635
https://github.com/droolsjbpm/guvnor/pull/241
https://github.com/droolsjbpm/kie-wb-common/pull/243
https://github.com/droolsjbpm/drools-wb/pull/122
https://github.com/droolsjbpm/kie-wb-distributions/pull/190
https://github.com/droolsjbpm/kie-docs/pull/41

**Comment by manstis** [comment]
I need to ensure this PR is JDK1.6 compatible.... will advise when fixed.

**Comment by manstis** [comment]
Re-wrote the affected code to be JDK1.6 compatible.. OK to review..

**Comment by csadilek** [comment]
6.4.x: e7e207daf8a13b23b2e9134b81ec1aba0e3ebf78

**Pull request closed without merging**
