### PR TITLE
BZ-1197649 - Updating addAtribute return type to FormStyleItem instea…

### PR DESCRIPTION
**Pull request by paulovmr**
…d of int.

### CODE REVIEW

**Comment by paulovmr** [comment]
Depends on:
https://github.com/uberfire/uberfire-extensions/pull/158

**Comment by manstis** [comment]
+1 to merge (when the ```uf-ext``` PR is merged).

**Comment by psiroky** [comment]
jenkins, retest this

**Comment by psiroky** [comment]
jenkins, retest this

**Comment by csadilek** [comment]
master: 93e1b4315af31e4c0355ab09151a7c871e3d4a9c

**Pull request closed without merging**
