### PR TITLE
[6.3.x] GUVNOR-2399: Errors retrieving LockInfo

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2399

This is the corollary of https://github.com/droolsjbpm/guvnor/pull/260 for 6.3.x

(cherry picked from commit 5d48a98d7fd12b8344778801aaf81a6380d5d6fa)

### CODE REVIEW

**Comment by Rikkola** [comment]
+1

**Comment by manstis** [comment]
Jenkins, please retest this.

**Comment by psiroky** [comment]
Is there a BZ for this? Generally 6.3.x branch only receives fixes if there is patch BZ associated with it (but there maybe exceptions...).

**Comment by manstis** [comment]
@psiroky No BZ.. I'll close this PR and request if QE want it backported...

**Comment by csadilek** [comment]
@psiroky @manstis I'd be very much in favour of back-porting this to 6.3.x. It's likely to come back later as an intermittent problem. Do you have any news here..can I not just cherry-pick ;)?

**Comment by csadilek** [comment]
6.3.x: d674e6fb482fe75da0acb8a17d558bc61464974f

**Comment by csadilek** [comment]
Added this commit as it's an important (although minor) issue that we don't want to run into in the future. We had other commits on 6.3.x since the last release that had no BZ either.

**Pull request closed without merging**
