### PR TITLE
Better arrow (U+2192) in Repository Structure title 6.3.x

### PR DESCRIPTION
**Pull request by yurloc**
Follow-up to #179. I have checked the docker image of 6.4 build and it looks OK in Firefox and IE so I would like to get it to 6.3.x.

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (but @etirelli is likely to ask #1 where's the BZ? and #2 was this approved to be in 6.3.x by productization, as we're pretty much in "blocker only mode").... ;)

**Comment by yurloc** [comment]
@manstis you're right. I forgot about the blocker only mode. I'll look if it's worth (and possible) filing a BZ and having it acked. Otherwise I'm OK if this PR will be scratched.

**Comment by etirelli** [comment]
@yurloc @manstis best to merge it to master only as we are in code freeze for 6.3.x

**Comment by porcelli** [comment]
closing as 6.3.x is on blocker mode. please submit to master

**Pull request closed without merging**
