### PR TITLE
GUVNOR-2339 : Test utils module for Guvnor

### PR DESCRIPTION
**Pull request by Rikkola**
Needs this one: https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/127

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by ederign** [comment]
Why not here? https://github.com/uberfire/uberfire/tree/master/uberfire-testing-utils

**Comment by Rikkola** [comment]
@ederign Not sure if you want Weld dependencies there? But that was where I originally planned to place these.

**Comment by ederign** [comment]
idk. what do you guys think?

Em qui, 14 de jan de 2016 às 15:15, Toni Rikkola <notifications@github.com>
escreveu:

**Comment by csadilek** [comment]
master: 63a94048180d74c018dd22f48504a912f9a83413

**Pull request closed without merging**
