### PR TITLE
GUVNOR-2346: added testcases

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
Please do not merge yet.

**Comment by csadilek** [comment]
Thanks, looks good to me but best for @manstis or @Rikkola to verify?

**Comment by manstis** [comment]
@jomarko, is this OK to review now?

**Comment by jomarko** [comment]
@manstis , yes, I think so

**Comment by Rikkola** [comment]
+1

**Comment by csadilek** [comment]
master: 4a7fd7a1df1e771f316637d5e569eff60d4b98c3

**Pull request closed without merging**
