### PR TITLE
BZ-1274685 - New Repository dialog validation broken when Managed Repository is checked

### PR DESCRIPTION
**Pull request by wmedvede**
- original bz fixed
    - MVP improvements
    - Tests added

(cherry picked from commit c28d95a4e001801e425ab4631487a9b363b82e62)

### CODE REVIEW

**Comment by wmedvede** [comment]
Peer PR for https://github.com/droolsjbpm/guvnor/pull/176

**Comment by wmedvede** [comment]
The following PRs are related to current PR and should be merged previously

1) https://github.com/uberfire/uberfire-extensions/pull/104

2) https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/95

**Comment by wmedvede** [comment]
@manstis 
Hello Mike, would you mind to review this PR?

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks!

master: 708823061234c91e48368289f49d108da6b33636

**Pull request closed without merging**
