### PR TITLE
User with no privileges for repository can view and modify assets in that repository

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by ederign** [comment]
6.4 : https://github.com/droolsjbpm/guvnor/pull/228

**Comment by ederign** [comment]
6.3: https://github.com/droolsjbpm/guvnor/pull/229

**Comment by psiroky** [comment]
Thanks for the PRs @ederign! These will nicely test the updated PR build setup for different target branches :)

**Comment by manstis** [comment]
Licenses for new files show 2015; but otherwise fine... +1 to merge.

**Comment by csadilek** [comment]
master: e16fbbd3605b3e228c6b630229b8d5d569ce0978

**Pull request closed without merging**
